#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Mon Jan 18 15:02:50 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(".\\src\\logo.png", wx.BITMAP_TYPE_ANY))
        self.btn_start = wx.Button(self, wx.ID_ANY, _("Start"))
        self.btn_stop = wx.Button(self, wx.ID_ANY, _("Stop"))
        self.list_ctrl_1 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnStart, self.btn_start)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.btn_stop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.btn_start, 0, 0, 0)
        grid_sizer_2.Add(self.btn_stop, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def OnStart(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnStart' not implemented!"
        event.Skip()

    def OnStop(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnStop' not implemented!"
        event.Skip()

# end of class MyFrame
