#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.7.1 on Mon Jan 04 11:06:38 2016
#
import time
import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

resultrows = [["1", "Power Output ", "40", "41", "41.8", "dBm", "PASS"],
        ["2", "ACLR ", "-99", "-50", "-55", "dBc", "PASS"],
        ["3", "Spurious ", "-50", "-40", "-45", "dBm", "PASS"]
        ]


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(".\logo.png", wx.BITMAP_TYPE_ANY))
        self.btn_start = wx.Button(self, wx.ID_ANY, ("Start"))
        self.btn_stop = wx.Button(self, wx.ID_ANY, ("Stop"))
        self.list_ctrl = wx.ListCtrl(self, wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize,
         style=wx.LC_REPORT | wx.LC_HRULES | wx.LC_VRULES , validator=wx.DefaultValidator, name=wx.ListCtrlNameStr)
        
        self.list_ctrl.InsertColumn(0, 'ID')
        self.list_ctrl.InsertColumn(1, 'Test Name', width=500)
        self.list_ctrl.InsertColumn(2, 'Low Limit', width=75)
        self.list_ctrl.InsertColumn(3, 'Upper Limit', width=75)
        self.list_ctrl.InsertColumn(4, 'Result', width=75)
        self.list_ctrl.InsertColumn(5, 'Unit', width=50)
        self.list_ctrl.InsertColumn(6, 'Status', width=75)


        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnStart, self.btn_start)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.btn_stop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(("TestGUI"))
        self.SetSize((1024, 768))
        self.SetBackgroundColour(wx.Colour(232, 232, 232))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.btn_start, 0, 0, 0)
        grid_sizer_2.Add(self.btn_stop, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, 0, 0)
        grid_sizer_1.Add(self.list_ctrl, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
#         grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def OnStart(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnStart' not implemented!")
        
        index = 0
        for row in resultrows:
            self.list_ctrl.InsertStringItem(index, row[0])
            self.list_ctrl.SetStringItem(index, 1, row[1])
            self.list_ctrl.SetStringItem(index, 2, row[2])
            self.list_ctrl.SetStringItem(index, 3, row[3])
            self.list_ctrl.SetStringItem(index, 4, row[4])
            self.list_ctrl.SetStringItem(index, 5, row[5])
            self.list_ctrl.SetStringItem(index, 6, row[6])

            index += 1
            time.sleep(3)
            event.Skip()

    def OnStop(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnStop' not implemented!")
        self.Close()
        event.Skip()
        

# end of class MyFrame

if __name__ == '__main__':
    app = wx.App()
    # wx.InitAllImageHandlers()
    frame = MyFrame(None, -1 ,'')
    app.SetTopWindow(frame)
    
    frame.Show()
    
    app.MainLoop()
